// Generated by Skyramp v1.3.36 on 2026-07-24 21:01:55.984358199 +0000 UTC m=+666.792040001
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output alerts-new-alert-enabled-tooltip.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Alerts \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/alert_list_new_alert_tooltip_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';
import PageManager from '../../pages/page-manager.js';

const pageTimeout = 15000;

// Test data
const DESTINATION_NAME = "testbot-webhook-destination";
const DESTINATION_URL = "https://example.com/webhook";
const DESTINATION_TEMPLATE = "prebuilt_webhook";

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(1030000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page, testInfo);

    // Page objects
    const pm = new PageManager(page);

    await page.goto("http://localhost:5080/web");
    await pm.loginPage.login();

    await page.goto("http://localhost:5080/web/alerts?org_identifier=default");

    // Precondition: no destinations exist yet, so the "New alert" button is
    // disabled and its title falls back to the untranslated i18n key.
    const newAlertButton = page.locator('[data-test="alert-list-add-alert-btn"]');
    await expect(newAlertButton).toBeDisabled();

    // Create a destination (a prebuilt template already exists) so the
    // button's enabled-state condition (!destinations.length || !templates.length) is met.
    // kept inline: alertDestinationsPage.js's createDestination()/deleteDestination()
    // assert via @playwright/test's expect() internally, which rejects the
    // Skyramp-wrapped page/locator ("can be only used with Locator object").
    await page.locator('[data-test="alert-list-create-destination-btn"]').click();
    await page.locator('[data-test="alert-destination-list-add-alert-btn"]').click();
    await page.getByText('Custom Destination').click();
    await page.locator('[data-test="add-destination-name-input-field"]').fill(DESTINATION_NAME);
    await page.locator('[data-test="add-destination-template-select-trigger"]').click();
    await page.getByRole('option', { name: DESTINATION_TEMPLATE }).click();
    await page.locator('[data-test="add-destination-url-input-field"]').fill(DESTINATION_URL);
    await page.locator('[data-test="add-destination-submit-btn"]').click();

    await page.goto("http://localhost:5080/web/alerts?org_identifier=default");
    await newAlertButton.hover();

    // Core assertion for this PR: once a destination (and an existing template)
    // are in place, the "New alert" button must be enabled and its title/tooltip
    // must read "Create a new alert" instead of the old blank string.
    await expect(newAlertButton).toBeEnabled();
    await expect(newAlertButton).toHaveAttribute('title', 'Create a new alert');

    // Cleanup: remove the destination this test created.
    await page.goto("http://localhost:5080/web/settings/alert_destinations?org_identifier=default");
    await page.locator(`[data-test="alert-destination-list-${DESTINATION_NAME}-delete-destination"]`).click();
    await page.locator('[data-test="o-dialog-primary-btn"]').click();
});
