// Generated by Skyramp v1.3.36 on 2026-07-24 21:01:51.850152063 +0000 UTC m=+662.657833865
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output alerts-new-alert-disabled-tooltip-bug.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Alerts \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/alert_list_disabled_tooltip_bug_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';
import PageManager from '../../pages/page-manager.js';

const pageTimeout = 15000;

// Test data
const DESTINATION_NAME = "testbot-webhook-destination";

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page, testInfo);

    // Page objects
    const pm = new PageManager(page);

    await page.goto("http://localhost:5080/web/settings/alert_destinations?org_identifier=default");
    await pm.loginPage.login();

    // Idempotent cleanup: only delete the destination if a prior run (or the
    // agent's own exploration) left it behind — the Alerts page's disabled
    // "New alert" state under test just requires zero destinations to exist.
    // kept inline: alertDestinationsPage.js's deleteDestination() asserts via
    // @playwright/test's expect() internally, which rejects the Skyramp-wrapped
    // page/locator ("can be only used with Locator object") — inline instead.
    const deleteBtn = page.locator(`[data-test="alert-destination-list-${DESTINATION_NAME}-delete-destination"]`);
    if (await deleteBtn.isVisible().catch(() => false)) {
        await deleteBtn.click();
        await page.locator('[data-test="o-dialog-primary-btn"]').click();
    }

    await page.goto("http://localhost:5080/web/alerts?org_identifier=default");

    // The disabled "New alert" button's title attribute currently renders the
    // raw, untranslated i18n key "alerts.noDestinations" (en.json defines
    // "alerts.noDestinationsMsg" but not "alerts.noDestinations"). This
    // assertion documents that bug — it fails while the key is missing and
    // will pass once the translation is added.
    const newAlertButton = page.locator('[data-test="alert-list-add-alert-btn"]');
    await expect(newAlertButton).toBeVisible();
    await expect(newAlertButton).toBeDisabled();
    await expect(newAlertButton).not.toHaveAttribute('title', 'alerts.noDestinations');
});
